- alias: 'Notify if doors open after hours - weekdays'
  trigger:
    platform: state
    entity_id: sensor.back_door_access_control_12_9, sensor.front_door_access_control_13_9
    from: '23'
    to: '22'
  condition:
    condition: time
    after: '23:00:00'
    before: '05:45:00'
    weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
  action:
  - service: notify.pb
    data:
      message: > 
        {% if is_state("sensor.back_door_access_control_12_9", "22") %}Back Door{% elif is_state("sensor.front_door_access_control_13_9", "22") %}Front Door{% else %}Error{% endif %} is open!
  - service: homeassistant.turn_on
    entity_id: light.bedroom_light_level_4_0
  - service: media_player.play_media
    entity_id: media_player.tiffanys_desk_speakers
    data:
      media_content_type: "MUSIC"
      media_content_id: https://forristal.org/tornado_siren.mp3
