- alias: 'Turn on lights when opening doors'
  trigger:
    platform: state
    entity_id: sensor.back_door_access_control_12_9, sensor.front_door_access_control_13_9
    from: '23'
    to: '22'
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
    - condition: numeric_state
      entity_id: sensor.dark_sky_precip_probability
      above: 75
  action:
    service: homeassistant.turn_on
    entity_id: light.living_room_light_level_11_0
