- alias: 'Turn on lights when opening doors'
  trigger:
    platform: state
    entity_id: sensor.back_door_access_control_12_9, sensor.front_door_access_control_13_9
    from: '23'
    to: '22'
  condition:
    condition: template
    value_template: >
      {% if is_state("device_tracker.pforristal_ptfs7","home") %}
      false
      {% elif is_state("device_tracker.tforristal_trfs6","home") %}
      false
      { % else %}
      true
      {% endif %}

  action:
    service: notify.pb
    data:
      message: >
        Noone home and a door opened.
        Front door: {{states("sensor.ftdr")}}
        Back door: {{states("sensor.bkdr")}}
