- alias: 'Feed the cats breakfast'
  trigger:
    - platform: time
      at: "8:00"
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.catfud_marley
        - switch.catfud_utensi
 
- alias: 'Feed the cats lunch'
  trigger:
    - platform: time
      at: "16:00"
  action:
    - service: switch.turn_on
      entity_id:
        - switch.catfud_utensi
        - switch.catfud_marley
- alias: 'Feed the cats dinner'
  trigger:
    - platform: time
      at: "0:00"
  action:
    - service: switch.turn_on
      entity_id:
        - switch.catfud_utensi
        - switch.catfud_marley
