- alias: 'Feed the cats breakfast'
  trigger:
    - platform: time
      at: "0:00"
    - platform: time
      at: "8:00"
    - platform: time
      at: "16:00"
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.catfud_ziggy
        - switch.catfud_utensi
        - switch.catfud_marley
      
