- alias: 'Turn off the living room light off after the bus leaves'
  trigger:
    platform: time
    after: "6:30"
  condition: 
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: homeassistant.turn_off
    entity_id: switch.living_room_light_11_0 
