- alias: 'Turn on the living room light to make leaving for the bus easier'
  trigger:
    platform: time
    after: "5:30"
  condition: 
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: homeassistant.turn_on
    entity_id: switch.living_room_lamp_switch_8_0 
