- alias: 'Turn on bathroom fan when humidity is high'
  trigger:
    platform: numeric_state
    entity_id: sensor.master_bathroom_humidity
    above: 75
  condition:
    condition: state
    entity_id: switch.living_room_lamp_switch_8_0 
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.living_room_lamp_switch_8_0
  - wait_template: "{{ states.sensor.master_bedroom_humidity < 50 }}"
    timeout: 00:15:00
  - service: homeassistant.turn_off
    entity_id: switch.living_room_lamp_switch_8_0
