- alias: 'Turn on bathroom fan when humidity is high'
  trigger:
    platform: numeric_state
    entity_id: sensor.master_bathroom_humidity
    above: 75
  condition:
    condition: state
    entity_id: switch.living_room_lamp_switch_8_0 
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: switch.living_room_lamp_switch_8_0
