- alias: 'Turn on the snake tank light at 10:30AM during the weekend'
  trigger:
    platform: time
    after: "10:45"
  condition: 
  - condition: time
    weekday:
      - sat
      - sun
  action:
    service: switch.turn_on
    entity_id: switch.snake_tank_light_switch_5_0

