language: python
env: INSTALL_ARGS='homeassistant'
python:
  - '3.4'
matrix:
  fast_finish: true
  include:
    - env: INSTALL_ARGS='homeassistant==0.38.3'
    - env: INSTALL_ARGS='-e git+https://github.com/home-assistant/home-assistant.git#egg=Package'
  allow_failures:
    - env: INSTALL_ARGS='homeassistant'
    - env: INSTALL_ARGS='-e git+https://github.com/home-assistant/home-assistant.git#egg=Package'
cache:
  directories:
    - $HOME/.cache/pip
before_install:
- openssl aes-256-cbc -K $encrypted_d180a8fc4422_key -iv $encrypted_d180a8fc4422_iv
  -in secrets.yaml.enc -out secrets.yaml -d
install:
- pip3 install $INSTALL_ARGS
script:
- hass -c . --script check_config
