language: python
env: INSTALL_ARGS='homeassistant'
python:
  - "3.4"
matrix:
  fast_finish: true
  include:
    - python: "3.4"
      env: INSTALL_ARGS='homeassistant==0.38.4'
    - python: "3.4"
      env: INSTALL_ARGS='-e git+https://github.com/home-assistant/home-assistant.git@dev#egg=homeassistant'
  allow_failures:
    - python: "3.4"
      env: INSTALL_ARGS='homeassistant'
    - python: "3.4"
      env: INSTALL_ARGS='-e git+https://github.com/home-assistant/home-assistant.git@dev#egg=homeassistant'
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install $INSTALL_ARGS
  - hass --version
script:
  - hass -c . --script check_config
