language: python
dist: bionic
matrix:
  fast_finish: true
  include:
    - python: "3.7"
      env: HASS='homeassistant==0.103.4'
    - python: "3.7"
      env: HASS='homeassistant'
    - python: "3.7"
      env: HASS='https://github.com/home-assistant/home-assistant/archive/dev.zip'
  allow_failures:
    - python: "3.7"
      env: HASS='homeassistant'
    - python: "3.7"
      env: HASS='https://github.com/home-assistant/home-assistant/archive/dev.zip'
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
     - libdbd-pg-perl 
     - libsnmp-perl 
     - libssl-dev 
     - libio-socket-ssl-perl
     - curl 
     - postgresql 
     - build-essential
     - libavformat-dev 
     - libavcodec-dev 
     - libavdevice-dev 
     - libavutil-dev 
     - libswscale-dev 
     - libswresample-dev 
     - libavfilter-dev 
     - libudev-dev
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - pip3 install --force-reinstall certifi
install:
  - pip3 install $HASS
  - hass --version
script:
  - hass --config . --script check_config
