language: python
env: HASS='homeassistant==0.77.3'
python:
  - "3.7"
matrix:
  fast_finish: true
  include:
    - python: "3.7"
      env: HASS='homeassistant'
    - python: "3.7"
      env: HASS='https://github.com/home-assistant/home-assistant/archive/dev.zip'
  allow_failures:
    - python: "3.8"
      env: HASS='homeassistant'
    - python: "3.7"
      env: HASS='https://github.com/home-assistant/home-assistant/archive/dev.zip'
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install $HASS
  - hass --version
script:
  - hass --config . --script check_config
