homeassistant:
  name: Home
  unit_system: imperial
  time_zone: CST6CDT
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  customize: !include includes/customized.yaml

# Track the sun
sun:


http:
  api_password: !secret http_api
  
# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend
conversation:

#Automation
automation: !include_dir_merge_list includes/automation 

notify: !include includes/notify.yaml

script: !include_dir_merge_named  includes/scripts

scene: !include_dir_list  includes/scenes

mqtt: !include includes/mqtt.yaml
        

# Enables the frontend
frontend:


# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

group: !include includes/groups.yaml

#Z-Wave devices:

zwave:
  usb_path: /dev/zwave
  #polling_interval: 60000

switch: !include_dir_list includes/switches
light: !include_dir_list includes/lightss


emulated_hue:
  exposed_domains:
    - light
    - switch
    - imput_boolean

device_tracker:
  platform: owntracks
  max_gps_accuracy: 200
  track_new_devices: false


zone: !include_dir_merge_list includes/zones

media_player: !include_dir_merge_named includes/media_players
  



#SENSORS
sensor: !include_dir_merge_list includes/sensors

binary_sensor: !include_dir_merge_list includes/binary_sensors

panel_custom: !include_dir_merge_list panels

camera: !include includes/cameras.yaml

input_select: !include includes/input_select.yaml
