homeassistant:
  name: Home
  unit_system: imperial
  time_zone: CST6CDT
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  customize: !include customize.yaml
  customize_glob: !include includes/customize/customize_glob.yaml

# Track the sun
sun:

config:

logger:
  default: warning
  logs:
    requests.packages.urllib3.connectionpool: critical
    urllib3.connectionpool: error
    homeassistant.components.camera: error
    requests.packages.urllib3: critical


recorder:
  purge_interval: 1
  purge_keep_days: 7
  db_url: !secret db_url
  exclude:
    domains:
      - updater
    entities:
      - sensor.livingroom_rgbw_exporting
      - sensor.livingroom_rgbw_energy
      - sensor.livingroom_rgbw_power
      - sensor.livingroom_rgbw_power_2

http:
  api_password: !secret http_api
  base_url: !secret base_url
  
# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend
conversation:

#Automation
automation: !include automations.yaml
notify: !include includes/notify.yaml

script: !include_dir_merge_named  includes/scripts

scene: !include_dir_list  includes/scenes

mqtt: !include includes/mqtt.yaml

#light: !include_dir_list includes/lights

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300  

# Enables the frontend
frontend:


# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

group: !include includes/groups.yaml

sensor: !include_dir_merge_list includes/sensors/
binary_sensor: !include_dir_merge_list includes/binary_sensors/

weather:
  - platform: darksky
    api_key: !secret darksky_api
    units: us

#Z-Wave devices:

zwave:
  usb_path: /dev/ttyZWAVE
  device_config: !include zwave_device_config.yaml
  device_config_domain:
    light:
      polling_intensity: 2
      refresh_value: true
      delay: 2
    switch:
      polling_intensity: 2

zha:
  usb_path: /dev/ttyZIGBEE
  database_path: /config/zigbee.db

twilio:
  account_sid: !secret twilio_sid
  auth_token:  !secret twilio_auth

camera: !include includes/cameras.yaml

input_select: !include includes/input_select.yaml

input_number: 
  mbr_setpoint:
    name: "Master Bedroom Setpoint"
    min: 65
    max: 85
    unit_of_measurement: "째F"
  lr_setpoint:
    name: "Living Room Setpoint"
    min: 65
    max: 85
    unit_of_measurement: "째F"
  mbr_actual:
    name: "Master Bedroom AC Setting"
    min: 65
    max: 85
    unit_of_measurement: "째F"
  lr_actual:
    name: "Living Room AC Setting"
    min: 65
    max: 85
    unit_of_measurement: "째F"
  

octoprint:
  host: !secret octo_host
  api_key: !secret octo_api
  bed: true
  number_of_tools: 1

zoneminder:
  host: !secret zm_host
  username: !secret zm_user
  password: !secret zm_pass

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
    aliases:
      099b3ea38fbc011cc22716271c58e12a2a110395: 'Everywhere'
  - platform: vizio
    host: 10.13.13.104
    access_token: !secret vizio_pf
    name: Patricks Desk
    suppress_warning: true
  - platform: vizio
    host: 10.13.13.112
    access_token: !secret vizio_tf
    name: Tiffanys Desk
    suppress_warning: true

habitica:
  - api_user: !secret habitica_user
    api_key: !secret habitica_key

switch:  !include_dir_merge_list includes/switches/

device_tracker:
  - platform: unifi
    host: unifi
    username: !secret unifi_user
    password: !secret unifi_pass
    verify_ssl: false
    ssid_filter:
      - 'Cosmic AC'
zone: !include_dir_merge_list includes/zones/
