homeassistant:
  name: Home
  unit_system: imperial
  time_zone: CST6CDT
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  customize: !include includes/customize/customized.yaml
  customize_glob: !include includes/customize/customize_glob.yaml

# Track the sun
sun:

config:

recorder:
  exclude:
    entities:
      - sensor.rgbw_exporting_3_32
      - sensor.rgbw_power_3_8
      - sensor.rgbw_power_3_4
      - sensor.rgbw_energy_3_0

http:
  api_password: !secret http_api
  
# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend
conversation:

#Automation
automation: !include_dir_merge_list includes/automation 

notify: !include includes/notify.yaml

script: !include_dir_merge_named  includes/scripts

scene: !include_dir_list  includes/scenes

mqtt: !include includes/mqtt.yaml
 
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300  

# Enables the frontend
frontend:


# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

group: !include includes/groups.yaml

#Z-Wave devices:

zwave:
  usb_path: /dev/zwave
  device_config: !include zwave_device_config.yaml
  device_config_domain:
    light:
      polling_intensity: 2
      refresh_value: true
      delay: 2
    switch:
      polling_intensity: 2

emulated_hue:
  type: alexa
  exposed_domains:
    - light
    - switch
    - fan
    - input_boolean

twilio:
  account_sid: !secret twilio_sid
  auth_token:  !secret twilio_auth

camera: !include includes/cameras.yaml

input_select: !include includes/input_select.yaml
