title: Forristal Home
views:
  - title: Home
    id: home
    icon: mdi:home
    cards:
      - type: horizontal-stack
        cards:
          - type: conditional
            conditions:
              - entity: binary_sensor.trash
                state: true
            card:
              type: entities
              show_header_toggle: false
              entities:
                - binary_sensor.trash
          - type: conditional
            conditions:
              - entity: binary_sensor.recycling
                state: true
            card:
              type: entities
              show_header_toggle: false
              entities:
                - binary_sensor.recycling
      - type: horizontal-stack
        cards:
          - type: gauge
            entity: sensor.griddy
            title: Griddy
            unit_of_measurement: ¢
            severity:
              green: 0
              yellow: 5
              red: 20
          - type: gauge
            entity: sensor.current_uv_index
            title: UV Index
            max: 10
            unit_of_measurement: 'UV'
            severity:
              green: 0
              yellow: 3
              red: 5
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: device_tracker.pforristal_ptfs9
                state_not: home
            card:
              type: map
              aspect_ratio: 50%
              entities:
                - device_tracker.pforristal_ptfs9
                - zone.home
          - type: conditional
            conditions:
              - entity: device_tracker.tforristal_trfs8
                state_not: home
            card:
              type: map
              aspect_ratio: 50%
              entities:
                - device_tracker.tforristal_trfs8
                - zone.home
      - type: weather-forecast
        entity: weather.dark_sky   
  - title: Cameras
    id: cameras
    icon: mdi:cctv
    cards: 
      - type: picture-glance
        title: Front Door
        entities:
          - camera.front_porch
          - sensor.ftdr
        camera_image: camera.front_porch
      - type: picture-glance
        title: Front Yard
        entities:
          - camera.front_wide
          - sensor.mailbox
        camera_image: camera.front_wide
      - type: picture-glance
        title: Back Porch
        entities:
          - camera.backporch
          - sensor.bkdr
          - switch.back_porch_switch_3
          - switch.back_porch_switch_2
        camera_image: camera.backporch
      - type: picture-glance
        title: Side/Back Yard
        entities:
          - camera.side_back
        camera_image: camera.side_back


  - title: Living Room
    id: living
    icon: mdi:sofa
    cards:
      - type: entities
        id: livingroom_lights
        title: Lights
        entities:
          - light.livingroom_light_level
          - light.patricks_desk_light
          - light.tiffanys_desk_light
          - light.livingroom_rgbw_level
      - type: entities
        title: Switches
        show_header_toggle: false
        entities:
          - switch.solder_station_plug_switch
      - type: entities
        title: TVs
        entities:
          - media_player.patricks_desk
      - type: glance
        title: Sensors
        entities:
          - entity: sensor.ftdr
          - entity: sensor.livingroom_temperature
            name: Temp
          - entity: sensor.livingroom_humidity
            name: Humidity
          - entity: sensor.livingroom_pressure
            name: Pressure
          - entity: sensor.griddy
            name: Griddy
            icon: mdi:cash
      - type: glance
        show_state: false
        title: A/C
        entities:
          - entity: input_number.lr_setpoint
          - entity: switch.livingroom_ac_power
            name: A/C
          - entity: switch.livingroom_ac_mode
            name: Cool
            tap_action: call-service
            service: switch.turn_on
            icon: mdi:snowflake
          - entity: switch.livingroom_ac_mode
            name: Fan-Only
            tap_action: call-service
            service: switch.turn_off
            icon: mdi:fan
  - title: Kitchen
    id: kitchen
    icon: mdi:fridge
    cards:
      - type: entities
        title: Lights
        entities:
          - light.kitchen_stove_light
          - light.kitchen_light
          - switch.kitchen_sink_light_switch
      - type: glance
        title: Sensors
        entities:
          - entity: sensor.bkdr
          - entity: sensor.kitchen_temperature
            name: Temp
          - entity: sensor.kitchen_humidity
            name: Humidity

  - title: Master Bedroom
    id: masterbr
    icon: mdi:hotel
    cards:
      - type: entities
        title: Lights
        entities:
          - light.bedroom_light_level
          - switch.nightstand_light_switch
          - switch.orange_light_switch
          - switch.bed_glow_switch
          - switch.snake_tank_light_switch
 
      - type: glance
        title: Sensors
        entities:
          - entity: sensor.master_bedroom_temperature
            name: Temp
          - entity: sensor.master_bedroom_humidity
            name: Humidity
      - type: glance
        title: Snake Tank
        entities:
          - entity: sensor.snake_tank_temp__cold_side
            name: Cold Side
          - entity: sensor.snake_tank_temp__hot_side
            name: Hot Side
          - entity: switch.snake_tank_light_switch
            name: Light
  - title: Hobby Room
    id: hobby
    icon: mdi:flask
    cards:
      - type: entities
        title: Lights
        entities:
          - light.hobby_room_light
          - light.sewing_light
      - type: picture-glance
        title: Maker Select
        entities:
          -  camera.octoprint
          -  sensor.maker_select_current_state
          -  sensor.maker_select_job_percentage
          -  sensor.maker_select_actual_tool0_temp
          -  sensor.maker_select_actual_bed_temp
          -  switch.3d_printer_plug_switch
        camera_image: camera.octoprint
  - title: Map
    id: map
    icon: mdi:earth
    panel: true
    cards:
      - type: map
        entities:
          - device_tracker.pforristal_ptfs9
          - device_tracker.tforristal_trfs8
          - zone.home
          - zone.work__pf
          - zone.work__tf
