title: Forristal Home
views:
  - title: Home
    id: home
    icon: mdi:home
    cards:
      - id: 6d76de64fe8c45799945a2ca1cc3a033  # Automatically created id
        type: horizontal-stack
        cards:
          - type: conditional
            conditions:
              - entity: binary_sensor.trash
                state: true
            card:
              type: entities
              show_header_toggle: false
              entities:
                - binary_sensor.trash
          - type: conditional
            conditions:
              - entity: binary_sensor.recycling
                state: true
            card:
              type: entities
              show_header_toggle: false
              entities:
                - binary_sensor.recycling
      - id: 77f8e22da4824b7fa5107b1d391e5e46  # Automatically created id
        type: horizontal-stack
        cards:
          - type: gauge
            entity: sensor.griddy
            title: Griddy
            unit_of_measurement: ¢
            severity:
              green: 0
              yellow: 5
              red: 20
          - type: gauge
            entity: sensor.current_uv_index
            title: UV Index
            max: 10
            unit_of_measurement: 'UV'
            severity:
              green: 0
              yellow: 3
              red: 5
      - id: b37f6046e3924dc695397882e246b6d1  # Automatically created id
        type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: device_tracker.pforristal_ptfs9
                state_not: home
            card:
              type: map
              aspect_ratio: 50%
              entities:
                - device_tracker.pforristal_ptfs9
                - zone.home
          - type: conditional
            conditions:
              - entity: device_tracker.tforristal_trfs8
                state_not: home
            card:
              type: map
              aspect_ratio: 50%
              entities:
                - device_tracker.tforristal_trfs8
                - zone.home
      - id: ae94c378115f4bc7a38d4540ee09d160  # Automatically created id
        type: weather-forecast
        entity: weather.dark_sky
  - title: Cameras
    id: cameras
    icon: mdi:cctv
    cards:
      - id: 1c708b7b4b6a4e548862a380cd3dfe4f  # Automatically created id
        type: picture-glance
        title: Front Door
        entities:
          - camera.front_porch
          - sensor.ftdr
        camera_image: camera.front_porch
      - id: c8682ea784ad470fb0cac3b9b34fa09c  # Automatically created id
        type: picture-glance
        title: Front Yard
        entities:
          - camera.front_wide
          - sensor.mailbox
        camera_image: camera.front_wide
      - id: b47dcec387104b8288d9d95b5c7334a9  # Automatically created id
        type: picture-glance
        title: Back Porch
        entities:
          - camera.back_porch
          - sensor.bkdr
          - switch.back_porch_switch_3
          - switch.back_porch_switch_2
        camera_image: camera.back_porch
      - id: 5a1c7c01dd274f6d82684092f085835f  # Automatically created id
        type: picture-glance
        title: Side/Back Yard
        entities:
          - camera.side_back
        camera_image: camera.side_back


  - title: Living Room
    id: living
    icon: mdi:sofa
    cards:
      - type: entities
        id: livingroom_lights
        title: Lights
        entities:
          - light.livingroom_light_level
          - light.patricks_desk_light
          - light.tiffanys_desk_light
          - light.livingroom_rgbw_level
      - id: b2b1a03dff54427aba32627bbfa8e576  # Automatically created id
        type: entities
        title: Switches
        show_header_toggle: false
        entities:
          - switch.solder_station_plug_switch
      - id: 2fe32a10d1b84969bfebda26d8f1a9cf  # Automatically created id
        type: entities
        title: TVs
        entities:
          - media_player.patricks_desk
      - id: 36753415a4874a0f9b200cab701192ad  # Automatically created id
        type: glance
        title: Sensors
        entities:
          - entity: sensor.ftdr
          - entity: sensor.livingroom_temperature
            name: Temp
          - entity: sensor.livingroom_humidity
            name: Humidity
          - entity: sensor.livingroom_pressure
            name: Pressure
          - entity: sensor.griddy
            name: Griddy
            icon: mdi:cash
      - id: b0f6d91bbcde4574a45cd69aa1d6704f  # Automatically created id
        type: glance
        show_state: false
        title: A/C
        entities:
          - entity: input_number.lr_setpoint
          - entity: switch.livingroom_ac_power
            name: A/C
          - entity: switch.livingroom_ac_mode
            name: Cool
            tap_action: call-service
            service: switch.turn_on
            icon: mdi:snowflake
          - entity: switch.livingroom_ac_mode
            name: Fan-Only
            tap_action: call-service
            service: switch.turn_off
            icon: mdi:fan
  - title: Kitchen
    id: kitchen
    icon: mdi:fridge
    cards:
      - id: ad7db8f5d1d44983ad00d91e4b587968  # Automatically created id
        type: entities
        title: Lights
        entities:
          - light.kitchen_stove_light
          - light.kitchen_light
          - switch.kitchen_sink_light_switch
      - id: 3f884788509e45f49b947b5e73d95a56  # Automatically created id
        type: glance
        title: Sensors
        entities:
          - entity: sensor.bkdr
          - entity: sensor.kitchen_temperature
            name: Temp
          - entity: sensor.kitchen_humidity
            name: Humidity

  - title: Master Bedroom
    id: masterbr
    icon: mdi:hotel
    cards:
      - id: bf6d3eedbfa54feeb1ba379f395c40fc  # Automatically created id
        type: entities
        title: Lights
        entities:
          - light.bedroom_light_level
          - switch.nightstand_light_switch
          - switch.orange_light_switch
          - switch.bed_glow_switch
          - switch.snake_tank_light_switch

      - id: 49f9f111f4b5477ab2dca38f37a9b0c6  # Automatically created id
        type: glance
        title: Sensors
        entities:
          - entity: sensor.master_bedroom_temperature
            name: Temp
          - entity: sensor.master_bedroom_humidity
            name: Humidity
      - id: 2ef09726f8884e13894404262f1daddc  # Automatically created id
        type: glance
        title: Snake Tank
        entities:
          - entity: sensor.snake_tank_temp__cold_side
            name: Cold Side
          - entity: sensor.snake_tank_temp__hot_side
            name: Hot Side
          - entity: switch.snake_tank_light_switch
            name: Light
  - title: Hobby Room
    id: hobby
    icon: mdi:flask
    cards:
      - id: 609b0daa55c54fab9983e48276469549  # Automatically created id
        type: entities
        title: Lights
        entities:
          - light.hobby_room_light
          - light.sewing_light
      - id: 20063cec9af54180a2ab533c08971b59  # Automatically created id
        type: picture-glance
        title: Maker Select
        entities:
          - camera.octoprint
          - sensor.maker_select_current_state
          - sensor.maker_select_job_percentage
          - sensor.maker_select_actual_tool0_temp
          - sensor.maker_select_actual_bed_temp
          - switch.3d_printer_plug_switch
        camera_image: camera.octoprint
  - title: Map
    id: map
    icon: mdi:earth
    panel: true
    cards:
      - id: 000b8ac8f0184ae7b5efb4b2d9577690  # Automatically created id
        type: map
        entities:
          - device_tracker.pforristal_ptfs9
          - device_tracker.tforristal_trfs8
          - zone.home
          - zone.work__pf
          - zone.work__tf
          - zone.central_market
          - zone.heb_alabama
          - zone.heb_bellaire
          - zone.heb_buffalo
          - zone.costco_greenway

