##############################################################################
# Automations and required components to display information messages on HASP

input_text:
  hasp_hasp_lr_messagetext:
    name: hasp_lr Message Text
    icon: mdi:playlist-edit
    max: 126
  hasp_hasp_lr_messageqr:
    name: hasp_lr Message QR
    icon: mdi:qrcode-edit
    max: 47

input_number:
  hasp_hasp_lr_messagetime:
    name: hasp_lr Message Time
    icon: mdi:clock-end
    mode: box
    min: 1
    max: 600
    step: 1

group:
  hasp_lr_messagedisplay:
    name: hasp_lr Message Display
    view: no
    entities:
      - input_text.hasp_hasp_lr_messagetext
      - input_text.hasp_hasp_lr_messageqr
      - input_number.hasp_hasp_lr_messagetime
      - automation.hasp_hasp_lr_00_messagedisplaytext
      - automation.hasp_hasp_lr_00_messagedisplayqr
      - automation.hasp_hasp_lr_00_messagedisplaytextqr

automation:
##############################################################################
# Display text message only
  - alias: hasp_hasp_lr_00_messagedisplaytext
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/hasp_lr/command/p[0].b[1].txt'
        payload: '"{{ states.input_text.hasp_hasp_lr_messagetext.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/hasp_lr/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/hasp_lr/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/hasp_lr/command'
        payload: 'vis 1,1'
    - delay: '00:00:{{ states.input_number.hasp_hasp_lr_messagetime.state | int }}'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/hasp_lr/command/page'
        payload: '{{ states.input_number.hasp_hasp_lr_activepage.state | int }}'

##############################################################################
# Display qr message only
  - alias: hasp_hasp_lr_00_messagedisplayqr
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/hasp_lr/command/p[0].b[3].txt'
        payload: '"{{ states.input_text.hasp_hasp_lr_messageqr.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/hasp_lr/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/hasp_lr/command'
        payload: 'vis 1,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/hasp_lr/command'
        payload: 'vis 3,1'
    - delay: '00:00:{{ states.input_number.hasp_hasp_lr_messagetime.state | int }}'
    - service: mqtt.publish
      data:
        topic: 'hasp/hasp_lr/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/hasp_lr/command'
        payload: 'vis 1,1'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/hasp_lr/command/page'
        payload: '{{ states.input_number.hasp_hasp_lr_activepage.state | int }}'

##############################################################################
# Display text and qr message
  - alias: hasp_hasp_lr_00_messagedisplaytextqr
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/hasp_lr/command/p[0].b[1].txt'
        payload: '"{{ states.input_text.hasp_hasp_lr_messagetext.state }}"'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/hasp_lr/command/p[0].b[3].txt'
        payload: '"{{ states.input_text.hasp_hasp_lr_messageqr.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/hasp_lr/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/hasp_lr/command'
        payload: 'vis 1,1'
    - service: mqtt.publish
      data:
        topic: 'hasp/hasp_lr/command'
        payload: 'vis 3,1'
    - delay: '00:00:{{ states.input_number.hasp_hasp_lr_messagetime.state | int }}'
    - service: mqtt.publish
      data:
        topic: 'hasp/hasp_lr/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/hasp_lr/command/page'
        payload: '{{ states.input_number.hasp_hasp_lr_activepage.state | int }}'