##############################################################################
# The devices created below are essential to the page control automations
# and you'll probably want to carry them over to your own configuration
homeassistant:
  customize:
    input_number.hasp_hasp_lr_alarmcode1:
      hidden: true
    input_number.hasp_hasp_lr_alarmcode2:
      hidden: true
    input_number.hasp_hasp_lr_alarmcode3:
      hidden: true
    input_number.hasp_hasp_lr_alarmcode4:
      hidden: true

# Enable this iframe to integrate the HASP web admin panel in Hass.
# This will not work if you have SSL enabled, see details here:
# https://www.home-assistant.io/components/panel_iframe/
#
panel_iframe:
  hasp_lr:
    title: "hasp_lr"
    url: "http://hasp_lr"
    icon: "mdi:cellphone-text"

light:
  - platform: mqtt
    name: hasp_lr Backlight
    command_topic: "hasp/hasp_lr/light/switch"
    state_topic: "hasp/hasp_lr/light/state"
    brightness_state_topic: "hasp/hasp_lr/brightness/state"
    brightness_command_topic: "hasp/hasp_lr/brightness/set"
    availability_topic: "hasp/hasp_lr/status"
    payload_available: "ON"
    payload_not_available: "OFF"

binary_sensor:
  - platform: mqtt
    name: hasp_lr Connected
    device_class: connectivity
    state_topic: "hasp/hasp_lr/status"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "hasp/hasp_lr/status"
    payload_available: "ON"
    payload_not_available: "OFF"

sensor:
  - platform: mqtt
    name: hasp_lr Sensor
    state_topic: "hasp/hasp_lr/status"
    availability_topic: "hasp/hasp_lr/status"
    payload_available: "ON"
    payload_not_available: "OFF"
    json_attributes_topic:  "hasp/hasp_lr/sensor"

input_text:
  hasp_hasp_lr_pagebutton1label:
    name: hasp_lr Page 1 Label
    icon: mdi:book-open-page-variant
  hasp_hasp_lr_pagebutton2label:
    name: hasp_lr Page 2 Label
    icon: mdi:book-open-page-variant
  hasp_hasp_lr_pagebutton3label:
    name: hasp_lr Page 3 Label
    icon: mdi:book-open-page-variant

input_number:
  hasp_hasp_lr_pagebutton1page:
    name: hasp_lr Page 1 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_hasp_lr_pagebutton2page:
    name: hasp_lr Page 2 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_hasp_lr_pagebutton3page:
    name: hasp_lr Page 3 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_hasp_lr_activepage:
    name: hasp_lr Active Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_hasp_lr_alarmcode1:
    name: hasp_lr AlarmCode1
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_hasp_lr_alarmcode2:
    name: hasp_lr AlarmCode2
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_hasp_lr_alarmcode3:
    name: hasp_lr AlarmCode3
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_hasp_lr_alarmcode4:
    name: hasp_lr AlarmCode4
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1

group:
  hasp_lr:
    name: hasp_lr
    view: yes
    entities:
      - binary_sensor.hasp_lr_connected
      - sensor.hasp_lr_sensor
      - light.hasp_lr_backlight
      - group.hasp_lr_pageselect
      - group.hasp_lr_colors
      - group.hasp_lr_automations
  hasp_lr_pageselect:
    name: hasp_lr Page Selection
    view: no
    entities:
      - input_number.hasp_hasp_lr_activepage
      - input_number.hasp_hasp_lr_pagebutton1page
      - input_text.hasp_hasp_lr_pagebutton1label
      - input_number.hasp_hasp_lr_pagebutton2page
      - input_text.hasp_hasp_lr_pagebutton2label
      - input_number.hasp_hasp_lr_pagebutton3page
      - input_text.hasp_hasp_lr_pagebutton3label
  hasp_lr_automations:
    name: hasp_lr automations
    view: no
    entities:
      - automation.hasp_hasp_lr_00_firsttimesetup

automation:
##############################################################################
# Run first time setup commands
  - alias: hasp_hasp_lr_00_FirstTimeSetup
    trigger: []
    action:
      - service: automation.trigger
        data:
          entity_id: 'automation.hasp_hasp_lr_00_automationgroupupdate'
      - service: homeassistant.turn_on
        data:
          entity_id: 'group.hasp_lr_automations'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_hasp_lr_pagebutton1label'
          value: 'scenes'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_hasp_lr_pagebutton2label'
          value: 'status'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_hasp_lr_pagebutton3label'
          value: 'lights'
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_hasp_lr_pagebutton1page'
          value: 1
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_hasp_lr_pagebutton2page'
          value: 2
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_hasp_lr_pagebutton3page'
          value: 3
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_hasp_lr_activepage'
          value: 1
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_hasp_lr_selectedforegroundcolor'
          value: 0
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_hasp_lr_selectedbackgroundcolor'
          value: 65535
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_hasp_lr_unselectedforegroundcolor'
          value: 65535
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_hasp_lr_unselectedbackgroundcolor'
          value: 25388

##############################################################################
# Set automation group members on start - Thanks @Nightcat!
  - alias: hasp_hasp_lr_00_AutomationGroupUpdate
    trigger:
    - platform: homeassistant
      event: start
    action:
    - service: group.set
      data_template:
        object_id: "hasp_lr_automations"
        entities: >-
          {%- for item in states.automation if ((item.entity_id | lower).startswith('automation.hasp_hasp_lr_')) -%}
          {{ item.entity_id }}
          {% if not loop.last %}, {% endif %}
          {%- endfor -%}