##############################################################################
# Automations and required components to configure colors on the HASP panel
#
# Check out this site for easy color code selection and conversion:
# https://nodtem66.github.io/nextion-hmi-color-convert/index.html

input_number:
  hasp_hasp_lr_selectedforegroundcolor:
    name: hasp_lr Selected Foreground Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
  hasp_hasp_lr_selectedbackgroundcolor:
    name: hasp_lr Selected Background Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
  hasp_hasp_lr_unselectedforegroundcolor:
    name: hasp_lr Unselected Foreground Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
  hasp_hasp_lr_unselectedbackgroundcolor:
    name: hasp_lr Unselected Background Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
group:
  hasp_lr_colors:
    name: hasp_lr Colors
    view: no
    entities:
      - input_number.hasp_hasp_lr_selectedforegroundcolor
      - input_number.hasp_hasp_lr_selectedbackgroundcolor
      - input_number.hasp_hasp_lr_unselectedforegroundcolor
      - input_number.hasp_hasp_lr_unselectedbackgroundcolor
