- platform: broadlink
  host: 10.13.13.110
  mac: '78:0f:77:31:b3:2f'
  timeout: 15
  switches:
    livingroom_ac_power:
      friendly_name: "Living Room A/C Power"
      command_on: 'JgBYAAABKJQVEBYPFg8WMxYPFRAVEBUQFTUVEBU0Fg8VNRU1FTUVNRU1FQ8WDxUQFTUVEBUQFRAVDxU1FTUVNRUQFTUVNRU0FQAFQQABKEkVAAxZAAEnSRUADQU=' 
      command_off: 'JgBYAAABKJQVEBYPFg8WMxYPFRAVEBUQFTUVEBU0Fg8VNRU1FTUVNRU1FQ8WDxUQFTUVEBUQFRAVDxU1FTUVNRUQFTUVNRU0FQAFQQABKEkVAAxZAAEnSRUADQU='
    livingroom_ac_temp:  # on is +, off is -
      friendly_name: "Living Room A/C Temp"
      command_on: 'JgBQAAABKpEWDxYPFg8VNBYPFg8WDxYPFjQWDxU0Fg8WNBY0FjQWNBYPFjQWNBYzFg8WDxYPFg8WNBYPFg8VDxY0FjQWNBY0FgAFQAABKUgWAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABLJEWDxYPFQ8WNBYPFg8WDxYPFTUVDxY0Fg8WNBY0FjQWNBY0Fg8VNBY0Fg8WEBUPFg8WDxU0FhAVEBU0FjQWNBY0FQAFQQABKkcWAA0FAAAAAAAAAAA='
    livingroom_ac_mode:
      friendly_name: "Living Room A/C Mode" #on is cool, off is fan
      command_on: 'JgBYAAABKZIVDxUQFRAVNRUQFRAVDxUQFTUVEBU1FRAVNRU0FjQVNRU1FRAVEBU1FRAVDxUQFRAVEBU1FTUVEBU0FTUVNRU1FQAFQQABKEkVAAxaAAEoSBUADQU='
      command_off: 'JgBYAAABKJIVEBQQFRAVNRUQFRAVEBQQFTUVEBU1FRAVNRU0FjQVNRU1FTUVNRUQFRAVEBQQFRAVEBUQFRAVNBU1FTUVNRU1FQAFQQABKEkVAAxaAAEnSBUADQU='
    livingroom_ac_fan:
      friendly_name: "Living Room A/C Fan" # on is faster, off is slower
      command_on: 'JgBYAAABK5IVEBUPFRAVNRUQFRAVEBUQFDUVEBU1FRAVNRU1FTUVNBY0Fg8VEBUQFRAVEBUQFBAVEBU1FTUVNRU1FTUVNRU0FQAFQQABKEoVAAxaAAEoSBUADQU='
      command_off: 'JgBYAAABLJEWDxUPFg8WNBYPFg8WDxYPFTQWDxY0Fg8WNBY0FjQWNBYOFg8WNBYPFg8WDxYPFQ8WNBY0FRAWNBU1FDYVNRU0FgAFQAABKEoVAAxaAAEoSBYADQU='
    livingroom_ac_fan_auto:
      friendly_name: "Living Room A/C Auto Fan"
      command_on:  'JgBYAAABK5EWDhYPFg8WNBYPFg8WDxUPFjQWDxY0Fg8WNBY0FjMWNBY0FjQWNBY0Fg8WDxYOFg8WDxYPFg8WDxY0FTUVNBY0FgAFQAABKUgWAAxZAAEpRxYADQU='

