- platform: broadlink
    host: 10.13.13.110
    mac: '78:0f:77:31:b3:2f'
    timeout: 15
    switches:
      livingroom_ac_power:
        friendly_name: "Living Room A/C Power"
        command_on: 'JgDKAJGQEzQRExE1EjYSEhAUEDUSEhISETUTEhESEjQTNRETEDcSERM0EjURNhI2ERIRNhI1EzMTEhISERMRExE0EhMSERE1EzQSNRMREhISERISEhIRExESExESNRM0EjURNhI1EayQkBM0EhISNRE3ERISEhE1ERITERM0ExEVDxE1EzURExA2EhISNRE2EjQQNxMSEjQSNBQ0FBESERESEhMPNhEUERISNRI2EjMTEhISEhERFBEREhITERISETUSNhE1EjUSNRMADQUAAAAAAAAAAAAAAAAAAA==' 
        command_off: 'JgDKAJGQEzQRExE1EjYSEhAUEDUSEhISETUTEhESEjQTNRETEDcSERM0EjURNhI2ERIRNhI1EzMTEhISERMRExE0EhMSERE1EzQSNRMREhISERISEhIRExESExESNRM0EjURNhI1EayQkBM0EhISNRE3ERISEhE1ERITERM0ExEVDxE1EzURExA2EhISNRE2EjQQNxMSEjQSNBQ0FBESERESEhMPNhEUERISNRI2EjMTEhISEhERFBEREhITERISETUSNhE1EjUSNRMADQUAAAAAAAAAAAAAAAAAAA==' 
