sensor:
  - platform: darksky
    api_key: !secret darksky_api
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    hourly_forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 7
      - 8
    monitored_conditions:
      - summary
      - icon
      - temperature
      - precip_type
      - precip_intensity
      - precip_probability
      - apparent_temperature
      - wind_speed
      - wind_gust
      - wind_bearing
      - humidity
      - pressure
      - ozone
      - cloud_cover
      - uv_index
      - moon_phase
      - nearest_storm_distance
    scan_interval: '00:10'
