- platform: template
  sensors:
    bkdr:
      friendly_name: "Back Door"
      value_template: '{% if is_state("sensor.back_dr_access_control","22") %}Open{% elif is_state("sensor.back_dr_access_control","23") %}Closed{% else %}Error{% endif %}'
      icon_template:  '{% if is_state("sensor.back_dr_access_control","22") %}mdi:door-open{% elif is_state("sensor.back_dr_access_control","23") %}mdi:door-closed{% else %}mdi:close-circle{% endif %}'
    ftdr:
      friendly_name: "Front Door"
      value_template: '{% if is_state("sensor.front_dr_access_control","22") %}Open{% elif is_state("sensor.front_dr_access_control","23") %}Closed{% else %}Error{% endif %}'
      icon_template: '{% if is_state("sensor.front_dr_access_control","22") %}mdi:door-open{% elif is_state("sensor.front_dr_access_control","23") %}mdi:door-closed{% else %}mdi:close-circle{% endif %}'

