- platform: mqtt
  state_topic: "hass/enviro/5c:cf:7f:c3:cb:5e"
  unit_of_measurement: "°F"
  name: "Kitchen Temperature"
  value_template: '{{  value_json.temperature  }}'

- platform: mqtt
  state_topic: "hass/enviro/5c:cf:7f:c3:cb:5e"
  unit_of_measurement: "%"
  name: "Kitchen Humidity"
  value_template: '{{  value_json.humidity  }}'
