- platform: mqtt
  state_topic: "hass/5c:cf:7f:c3:cb:5e/enviro/temperature"
  unit_of_measurement: "°F"
  name: "Kitchen Temperature"

- platform: mqtt
  state_topic: "hass/5c:cf:7f:c3:cb:5e/enviro/humidity"
  unit_of_measurement: "%"
  name: "Kitchen Humidity"


