- platform: mqtt
  state_topic: "hass/mbr_enviro/enviro/temperature"
  unit_of_measurement: "°F"
  name: "Master Bedroom Temperature"

- platform: mqtt
  state_topic: "hass/mbr_enviro/enviro/humidity"
  unit_of_measurement: "%"
  name: "Master Bedroom Humidity"

- platform: mqtt
  state_topic: "hass/mbr_enviro/enviro/pressure"
  unit_of_measurement: "mbar"
  name: "Master Bedroom Pressure"

