- platform: mqtt
  state_topic: "hass/enviro/5c:cf:7f:c3:ae:21"
  unit_of_measurement: "°F"
  name: "Master Bedroom Temperature"
  value_template: '{{  value_json.temperature  }}'

- platform: mqtt
  state_topic: "hass/enviro/5c:cf:7f:c3:ae:21"
  unit_of_measurement: "%"
  name: "Master Bedroom Humidity"
  value_template: '{{  value_json.humidity  }}'
