- platform: mqtt
  state_topic: "hass/5c:cf:7f:c3:cb:5d/enviro/temperature"
  unit_of_measurement: "°F"
  name: "Master Bathroom Temperature"

- platform: mqtt
  state_topic: "hass/5c:cf:7f:c3:cb:5d/enviro/humidity"
  unit_of_measurement: "%"
  name: "Master Bathroom Humidity"

