esphome:
  name: crystalball
  platform: ESP8266
  board: d1_mini_pro

  on_boot:
    then:
      - light.turn_on:
          id: crystalball
          effect: wipe
          brightness: .8

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_psk

ota:
  password: !secret iot_ota_pw
api:
  password: !secret iot_api_pw

# Enable logging
logger:



light:
  - platform: fastled_clockless
    name: crystalball
    chipset: WS2812B
    pin: D4
    num_leds: 12
    rgb_order: GRB
    id: crystalball
    effects: 
      - strobe:
      - flicker:
      - addressable_color_wipe:
          name: wipe
          colors:
            - red: 100%
              blue: 0%
              green: 0%
              num_leds: 2
            - red: 100%
              green: 100%
              blue: 0%
              num_leds: 2
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
      - addressable_rainbow:
          speed: 10
          width: 7